# Generated by Django 4.2.6 on 2023-10-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_name', models.CharField(max_length=100)),
                ('bot_token', models.CharField(max_length=100)),
                ('bot_link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bot',
            },
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(max_length=250)),
                ('channel_link', models.CharField(max_length=250)),
                ('channel_id', models.CharField(max_length=100)),
                ('my_channel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'channels',
                'unique_together': {('channel_id', 'my_channel')},
            },
        ),
        migrations.CreateModel(
            name='Client_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.CharField(max_length=100)),
                ('api_hash', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('session', models.FileField(blank=True, null=True, upload_to='session')),
            ],
            options={
                'db_table': 'client_settings',
            },
        ),
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('is_caption', models.BooleanField(default=False)),
                ('is_photo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'filename',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('caption', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
                ('channel_from', models.CharField(max_length=100)),
                ('delete_status', models.BooleanField(default=True)),
                ('single_photo', models.BooleanField(default=False)),
                ('send_status', models.BooleanField(default=False)),
                ('photo_count', models.IntegerField(default=0)),
                ('end', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='KeywordChannelAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.channels')),
            ],
            options={
                'db_table': 'keywordchannelads',
            },
        ),
        migrations.CreateModel(
            name='Channel_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.bot')),
                ('from_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_channel_configs', to='client.channels')),
                ('to_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_channel_configs', to='client.channels')),
            ],
            options={
                'db_table': 'channel_config',
                'unique_together': {('from_channel', 'to_channel')},
            },
        ),
    ]
