# Generated by Django 4.2.6 on 2023-11-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('is_caption', models.BooleanField(default=False)),
                ('is_photo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'filename',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('caption', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
                ('delete_status', models.BooleanField(default=True)),
                ('single_photo', models.BooleanField(default=False)),
                ('send_status', models.BooleanField(default=False)),
                ('photo_count', models.IntegerField(default=0)),
                ('ready', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('channel_from', models.ForeignKey(blank=True, limit_choices_to={'my_channel': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_channel_messages', to='setting_ads.channels')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
