# Generated by Django 4.2.6 on 2023-10-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_channel_config_to_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_settings',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
