# Generated by Django 4.2.6 on 2024-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_message_history_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_channel',
            field=models.BooleanField(default=False),
        ),
    ]
