# Generated by Django 4.2.6 on 2023-10-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_settings_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_config',
            name='from_channel',
            field=models.ForeignKey(blank=True, limit_choices_to={'my_channel': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_channel_configs', to='client.channels'),
        ),
        migrations.AlterField(
            model_name='channel_config',
            name='to_channel',
            field=models.ForeignKey(limit_choices_to={'my_channel': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_channel_configs', to='client.channels'),
        ),
    ]
