# Generated by Django 4.2.6 on 2023-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_channel_config_from_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
