# Generated by Django 4.2.6 on 2024-01-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_message_has_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_channel',
            field=models.BooleanField(default=False),
        ),
    ]
