# Generated by Django 4.2.6 on 2023-10-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_settings_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channels',
            unique_together={('channel_id', 'my_channel')},
        ),
    ]
