# Generated by Django 4.2.6 on 2023-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_bot_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
