# Generated by Django 4.2.6 on 2024-01-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_message_has_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='has_channel',
            field=models.BooleanField(default=True),
        ),
    ]
