# Generated by Django 4.2.6 on 2023-10-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_channels_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
