# Generated by Django 4.2.6 on 2023-10-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_message_message_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel_config',
            unique_together={('from_channel', 'to_channel')},
        ),
    ]
