# Generated by Django 4.2.6 on 2024-02-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting_ads.bot'),
        ),
    ]
