# Generated by Django 4.2.6 on 2023-11-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_config',
            name='from_channel',
            field=models.ForeignKey(blank=True, limit_choices_to={'my_channel': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_channel_configs', to='setting_ads.channels', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='keywordchannelads',
            unique_together={('text', 'channel')},
        ),
    ]
