# Generated by Django 4.2.6 on 2023-11-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_ads', '0002_alter_channels_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_post_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.BooleanField(default=False)),
                ('video_caption', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
                ('photo_caption', models.BooleanField(default=False)),
                ('caption', models.BooleanField(default=False)),
                ('text', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='channels',
            name='setting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting_ads.channel_post_setting'),
        ),
    ]
