# Generated by Django 4.2.6 on 2024-02-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_delete_message_history'),
        ('setting_ads', '0003_channel_post_setting_channels_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('from_channel', models.ForeignKey(blank=True, limit_choices_to={'my_channel': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_channel', to='setting_ads.channels')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.message')),
                ('to_channel', models.ForeignKey(blank=True, limit_choices_to={'my_channel': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_channel', to='setting_ads.channels')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting_ads.channel_type')),
            ],
            options={
                'db_table': 'timestamp',
                'abstract': False,
            },
        ),
    ]
