# Generated by Django 4.2.6 on 2023-11-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('setting_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'note',
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='SomeErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('error', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'some_errors',
                'db_table': 'some_errors',
            },
        ),
        migrations.CreateModel(
            name='Message_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.TextField()),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_log', to='client.message')),
            ],
            options={
                'verbose_name_plural': 'Message_log',
                'db_table': 'message_log',
            },
        ),
        migrations.CreateModel(
            name='Listening_channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('listening_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_channels', to='setting_ads.channels')),
            ],
            options={
                'verbose_name_plural': 'listening_channels',
                'db_table': 'listening_channels',
                'unique_together': {('channel_id', 'listening_channel')},
            },
        ),
    ]
