# Generated by Django 4.2.6 on 2023-11-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_ads', '0002_alter_channels_bot'),
        ('log_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listening_channels',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='listening_channels',
            name='listening_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_channels', to='setting_ads.channels', unique=True),
        ),
        migrations.RemoveField(
            model_name='listening_channels',
            name='channel_id',
        ),
    ]
