# Generated by Django 4.2.6 on 2023-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_log',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
