# Generated by Django 4.2.6 on 2023-11-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_ads', '0002_alter_channels_bot'),
        ('log_info', '0002_alter_listening_channels_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening_channels',
            name='listening_channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_channel', to='setting_ads.channels'),
        ),
    ]
